# Generated by Django 4.2.27 on 2026-03-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catID', models.AutoField(primary_key=True, serialize=False)),
                ('catName', models.CharField(max_length=20, verbose_name='分類名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cId', models.AutoField(primary_key=True, serialize=False)),
                ('cAccount', models.CharField(max_length=50, unique=True)),
                ('cPassword', models.CharField(max_length=128)),
                ('cName', models.CharField(max_length=20)),
                ('cSex', models.CharField(default='F', max_length=1)),
                ('cBirthday', models.DateField(blank=True, null=True)),
                ('cEmail', models.EmailField(max_length=100)),
                ('cPhone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fID', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=20)),
                ('fPrice', models.IntegerField()),
                ('fImage', models.ImageField(blank=True, default='food/default.jpg', null=True, upload_to='food/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oID', models.AutoField(primary_key=True, serialize=False)),
                ('oTotal', models.IntegerField(default=0)),
                ('oTime', models.DateTimeField(auto_now_add=True)),
                ('oStatus', models.CharField(default='處理中', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.order')),
            ],
        ),
    ]
