# Generated by Django 4.2.27 on 2026-03-10 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cAccount',
            field=models.CharField(max_length=50, unique=True, verbose_name='帳號'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cBirthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cEmail',
            field=models.EmailField(max_length=100, verbose_name='電子信箱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cName',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cPassword',
            field=models.CharField(max_length=128, verbose_name='加密密碼'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cPhone',
            field=models.CharField(max_length=50, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cSex',
            field=models.CharField(default='F', max_length=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fName',
            field=models.CharField(max_length=20, verbose_name='餐點名稱'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fPrice',
            field=models.IntegerField(verbose_name='單價'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer', verbose_name='會員'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oStatus',
            field=models.CharField(default='處理中', max_length=10, verbose_name='訂單狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='下單時間'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oTotal',
            field=models.IntegerField(default=0, verbose_name='總金額'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.food', verbose_name='餐點'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.IntegerField(verbose_name='小計'),
        ),
    ]
