# Generated by Django 4.2.27 on 2026-03-12 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customer_caccount_alter_customer_cbirthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fStock',
            field=models.IntegerField(default=0, verbose_name='當前庫存'),
        ),
        migrations.AddField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否供應中'),
        ),
        migrations.AddField(
            model_name='food',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, verbose_name='低庫存警示值'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.IntegerField(editable=False, verbose_name='小計'),
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='變動數量')),
                ('reason', models.CharField(choices=[('IN', '進貨/補貨'), ('OUT', '手動調整/損耗'), ('SALE', '銷售扣除')], default='SALE', max_length=10, verbose_name='變動類型')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='紀錄時間')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.food', verbose_name='餐點')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
