# Generated by Django 4.2.27 on 2026-03-12 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_food_fstock_food_is_active_food_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '餐點分類', 'verbose_name_plural': '餐點分類'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': '餐點', 'verbose_name_plural': '餐點'},
        ),
        migrations.RemoveField(
            model_name='food',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='food',
            name='add_qty',
            field=models.IntegerField(default=0, verbose_name='補貨'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catName',
            field=models.CharField(max_length=50, verbose_name='分類名稱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cEmail',
            field=models.EmailField(max_length=254, verbose_name='電子郵件'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cName',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cPassword',
            field=models.CharField(max_length=50, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cPhone',
            field=models.CharField(max_length=20, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cSex',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='myapp.category', verbose_name='所屬分類'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fImage',
            field=models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='餐點圖片'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fName',
            field=models.CharField(max_length=50, verbose_name='餐點名稱'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否供應'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer', verbose_name='客戶'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oStatus',
            field=models.CharField(default='處理中', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='訂單時間'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.food'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
