# Generated by Django 4.2.27 on 2026-03-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_category_options_alter_food_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客戶管理', 'verbose_name_plural': '客戶管理'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '訂單', 'verbose_name_plural': '訂單'},
        ),
        migrations.AlterModelOptions(
            name='stocklog',
            options={'ordering': ['-created_at'], 'verbose_name': '庫存變動紀錄', 'verbose_name_plural': '庫存變動紀錄'},
        ),
        migrations.AlterField(
            model_name='order',
            name='oStatus',
            field=models.CharField(choices=[('處理中', '處理中'), ('已完成', '已完成'), ('已結帳', '已結帳')], default='處理中', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='reason',
            field=models.CharField(choices=[('IN', '進貨/補貨'), ('SALE', '銷售扣除')], default='SALE', max_length=10, verbose_name='變動類型'),
        ),
    ]
