# Generated by Django 4.2.27 on 2026-03-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
